tidal-music/tidal-sdk-web

packages/player/package.json, packages/player/src/api/event/device-change.test.ts, packages/player/src/event-bus.test.ts, packages/player/src/index.test.ts, packages/player/src/index.ts, packages/player/src/internal/beacon/index.test.ts, packages/player/src/internal/handlers/get-asset-position.test.ts, packages/player/src/internal/handlers/get-media-product.test.ts, packages/player/src/internal/handlers/get-output-devices.test.ts, packages/player/src/internal/handlers/get-playback-context.test.ts, packages/player/src/internal/handlers/get-playback-state.test.ts, packages/player/src/internal/handlers/load.test.ts, packages/player/src/internal/handlers/set-next.test.ts, packages/player/src/internal/helpers/playback-info-resolver.test.ts, packages/player/src/internal/output-devices.test.ts, packages/player/src/internal/services/connection-handler.test.ts, packages/player/src/internal/services/pushkin.test.ts, packages/player/src/test-helpers.ts, packages/player/web-test-runner.config.js, pnpm-lock.yaml
=> Remove gh-pages from Player

.github/actions/build-module/action.yml, .github/workflows/lint.yml, .vscode/settings.json, package.json, packages/auth/package.json, packages/common/package.json, packages/event-producer/package.json, packages/player-web-components/package.json, packages/player/package.json, packages/template/package.json, packages/true-time/package.json
As "types" is too generic and is often used for generating types or including types.
=> "typecheck" instead of "types"

README.md
This is now done with Renovate
=> Update README.md removing dependency update section

renovate.json
Align with how we use it in different repos:
* Weekly schedule
* Group `Npm` patch and minor releases in one PR
=> Renovate tweaks

packages/auth/src/types.ts
Thanks @ziad-halabi9 for spotting this. We are not using this for web currently.
=> Remove unused type

packages/auth/examples/client-credentials.html, packages/auth/examples/limited-input-device.html, packages/auth/examples/login-redirect.html
The examples should be a bit more straight forward to use now.
=> To prevent unwanted states necessary input fields are now required

packages/auth/src/utils/utils.ts, packages/event-producer/src/bus.test.ts, packages/event-producer/src/monitor/monitor.test.ts, packages/event-producer/src/queue/worker.ts, packages/player/src/internal/beacon/worker.ts, packages/player/src/internal/helpers/generate-guid.ts, packages/player/src/internal/helpers/manifest-parser.ts, packages/player/src/internal/helpers/string-similarity.ts, packages/player/src/internal/output-devices.ts, packages/player/src/player/adaptations.ts, packages/player/src/player/filters.ts, packages/player/src/player/index.ts, packages/true-time/src/index.test.ts, tsconfig.json
Had to throw in some `undefined` guards, can be debated how well I did these :-P
This setting is highly recommended by the library we want to use for API types: https://openapi-ts.pages.dev/advanced#enable-nouncheckedindexedaccess-in-tsconfig
Also that TS dude: https://www.totaltypescript.com/tips/make-accessing-objects-safer-by-enabling-nouncheckedindexedaccess-in-tsconfig
=> Switch on TS noUncheckedIndexedAccess

.github/workflows/pull-request.yml, .github/workflows/unit-test.yml
sorry about that one it was trash
=> revert coverage check

packages/true-time/package.json
=> Bump TrueTime version to 0.2.0

.github/actions/setup/action.yml, .github/workflows/release-to-npm.yml
Hopefully the needed steps to hook NPM publishing up after a release is made here on GitHub
=> Automate publishing to NPM

packages/auth/package.json, packages/true-time/package.json
=> Bump packages again

packages/auth/package.json, packages/common/package.json
Need another round due to issues in publish pipeline
=> Bump auth and common

packages/event-producer/package.json, packages/event-producer/src/submit/submit.ts, packages/event-producer/src/utils/headerUtils.test.ts, packages/event-producer/src/utils/headerUtils.ts
header needs to be ```authorization``` NOT ```Authorization```
=> lower case authorization

packages/event-producer/src/index.ts
...so users of EventProducer can fill in legacy client/user fields with data from it.
=> [Event Producer] Export getConfig 

packages/player/src/internal/helpers/event-session.ts
Refactor #ensureDatabase to run without .datases() since Firefox does not support it. :(
=> [Player] Refactor #ensureDatabase to work in Firefox

packages/player/package.json
Release the fix in https://github.com/tidal-music/tidal-sdk-web/pull/97
=> Bump player version to v0.1.4

packages/event-producer/package.json
Making a release where getConfig is available, need that for #92
=> [Event Producer] Create release v2.0.4

.github/workflows/cypress.yml, .github/workflows/pull-request.yml
ref https://tidal-tech.slack.com/archives/C057S232400/p1711448333044919?thread_ts=1709296087.244089&cid=C057S232400
Note that I have never used path filters with this trigger, so if any issues arise that stands out as a candidate root cause.
=> Add merge_group trigger to enable merge queues

packages/auth/CHANGELOG.md, packages/auth/package.json
Minor release of auth, updating some examples and fixing two minor bugs
=> Bump auth and add changelog

renovate.json
I tried putting the "ignore" section in the wrong location
Should fix: #149
=> Try to fix Renovate

packages/player/src/api/interfaces.ts, packages/player/src/internal/constants.ts, packages/player/src/internal/helpers/manifest-parser.ts, packages/player/src/internal/helpers/playback-info-resolver.test.ts, packages/player/src/internal/helpers/playback-info-resolver.ts, packages/player/src/player/index.ts, packages/player/src/player/shakaPlayer.ts
This PR allows us to do playback of demo content
=> Added support for demo content

packages/player/src/internal/handlers/load.ts, packages/player/src/internal/handlers/set-next.ts, packages/player/src/player/shakaPlayer.ts
Fixed a bug where playback of demo content was not possible in Safari because of issues with FairPlay
=> Allow playback of demo content in Safari

packages/search/CHANGELOG.md, packages/search/src/searchAPI.d.ts
Generate new types, with some fixes and documentation improvements
=> Search module fixes

packages/catalogue/CHANGELOG.md, packages/catalogue/package.json, packages/catalogue/src/catalogueAPI.d.ts
Fixing `getSimilarTracks`, adding more examples and other cleanup
=> Import new Catalogue types

packages/auth/CHANGELOG.md, packages/auth/package.json
=> [Auth] Bumping version

packages/auth/CHANGELOG.md, packages/auth/package.json
=> Bump auth version

packages/catalogue/CHANGELOG.md, packages/catalogue/package.json, packages/catalogue/src/catalogueAPI.d.ts
Pull in new generated types, also newer version of generator (and fetch wrapper)
=> New Catalogue module release

packages/search/CHANGELOG.md, packages/search/package.json, packages/search/src/searchAPI.d.ts
Pull in new generated types, also newer version of generator (and fetch wrapper)
=> New Search module release

package.json, packages/catalogue/CHANGELOG.md, packages/catalogue/package.json, packages/catalogue/src/catalogueAPI.ts, packages/playlist/CHANGELOG.md, packages/playlist/package.json, packages/playlist/src/playlistAPI.ts, packages/search/CHANGELOG.md, packages/search/package.json, packages/search/src/searchAPI.ts, packages/user/CHANGELOG.md, packages/user/package.json, packages/user/src/userAPI.ts
Also adds a root `pnpm generateTypes` to run in all packages at once.
=> Sync latest types for API modules

packages/player/src/player/shakaPlayer.ts
Shaka cannot preload raw files and browser-based HLS on Safari. Ignore shaka error SRC_EQUALS_PRELOAD_NOT_SUPPORTED when that happens as the preload manager is saved and asserted on later. Remove the preloadManager check in skipToPreloadedMediaProduct so that non-preloadable content also play when skipped to.
=> [Player] Fix src= preloading with shaka

packages/player/src/internal/event-tracking/play-log/index.test.ts, packages/player/src/internal/event-tracking/play-log/index.ts, packages/player/src/internal/event-tracking/play-log/playback-session.ts, packages/player/src/internal/handlers/set-next.ts, packages/player/src/player/basePlayer.ts
Report correct productType for PlayLog events when playing demo content. UC for productType=demo.
=> Report correct productType for PlayLog events when playing demo content

packages/player/package.json, packages/player/scripts/version-dump.sh, packages/player/src/internal/handlers/get-player-version.ts, packages/player/vite-env.d.ts, packages/player/vite-legacy.config.ts, packages/player/vite.config.ts, pnpm-lock.yaml
For some reason the script didn't run properly in CI... Switching t vite plugin for getting version instead.
=> [Player] Fix getPlayerVersion

packages/player/src/player/fairplay-drm.ts, packages/player/src/player/shakaPlayer.ts
Make sure ready is awaited first so requests filters are available.
=> [Player] Fix 3016 issue on Safari

packages/player/CHANGELOG.md, packages/player/package.json
- Avoid shaka error 3016 on Safari. #218
=> [Player] Release v0.5.4

packages/api/README.md, packages/auth/README.md, packages/player/README.md
Also fix some broken links
Should resolve: #235
=> Document how to use API module in Node.js

packages/event-producer/src/queue/queue.ts
This will inline the sourcecode as Base64, hopefully more compatible with Vite dev mode.
=> Try other way of building web Worker for EP

packages/event-producer/CHANGELOG.md, packages/event-producer/package.json
Another attempt at improving EP Web Worker Vite compatibility
=> EP release

packages/player/src/config.ts, packages/player/src/internal/beacon/index.ts, packages/player/src/internal/beacon/play-log.ts, packages/player/src/internal/beacon/types.ts, packages/player/src/internal/beacon/worker.ts, packages/player/src/internal/constants.ts, packages/player/src/internal/event-tracking/play-log/index.ts, packages/player/src/internal/handlers/set-next.ts, packages/player/src/internal/helpers/get-is-post-paywall.ts, packages/player/src/internal/helpers/run-conditional-on-auth.ts, packages/player/src/internal/helpers/run-if-authorized-with-user.ts, packages/player/src/internal/index.ts, packages/player/src/player/basePlayer.ts
This PR adds the ability to send `play_log_open` events
=> Add play_log_open

package.json, packages/player/README.md, packages/player/package.json, packages/player/src/player/shakaPlayer.ts, packages/player/vite.config.ts, patches/shaka-player.patch, pnpm-lock.yaml, renovate.json
Also:
* refactor patching mechanism
* clean up README 
* add source-map support
* remove Shaka from Renovate ignore list
=> Player: Update shaka-player to v4.14

.github/workflows/check-tidalapi-spec.yml, .github/workflows/generate-tidal-api.yml
It was overwriting existing file before comparing new to old.
Also a small dryness fix (moved a repeated statement out of `if/else`). (And some whitespace.)
=> Fix API spec update check workflow

packages/common/CHANGELOG.md, packages/common/package.json
=> Common: Bump version to 0.2.0 and update changelog

packages/event-producer/CHANGELOG.md, packages/event-producer/package.json
Reordered Changelog with latest first
=> Update changelog and bump version to 2.4.0 for event producer

packages/player/src/internal/helpers/playback-info-resolver.ts, packages/player/src/player/shakaPlayer.ts
Refactor playback info types and clean up ShakaPlayer request handling
=> Remove more code for demo content type
