packages/player/src/api/event/device-change.test.ts
packages/player/src/event-bus.test.ts
packages/player/src/index.test.ts
packages/player/src/index.ts
packages/player/src/internal/beacon/index.test.ts
packages/player/src/internal/handlers/get-asset-position.test.ts
packages/player/src/internal/handlers/get-media-product.test.ts
packages/player/src/internal/handlers/get-output-devices.test.ts
packages/player/src/internal/handlers/get-playback-context.test.ts
packages/player/src/internal/handlers/get-playback-state.test.ts
packages/player/src/internal/handlers/load.test.ts
packages/player/src/internal/handlers/set-next.test.ts
packages/player/src/internal/helpers/playback-info-resolver.test.ts
packages/player/src/internal/output-devices.test.ts
packages/player/src/internal/services/connection-handler.test.ts
packages/player/src/internal/services/pushkin.test.ts
packages/player/src/test-helpers.ts
packages/player/web-test-runner.config.js

- Refactor web-test-runner to login the test user via auth module instead of a separate API call
- Skip test that required another streaming configuration than our test user have (a future TODO is adding 2 additional test users with the correct streaming configurations for the different players)
- Set concurrency to 1 on web test runner, seems auth module had issues with storage on higher concurrency

Refactor web test runner login to use Auth Module

---

packages/player/README.md

Refactor wording for linking.

---

package.json

As watch mode is not what we want for all package runs (and does not seem to work in any case).

Make running all tests in all package return results

---

packages/event-producer/src/submit/submit.test.ts
packages/event-producer/src/submit/submit.ts

Schedueler triggers sending of batches, submitter keeps sending 10 at a time until empty.

recursively submit until queue is empty

---

packages/player/src/player/shakaPlayer.ts

Refactor ShakaPlayer initialization from providing the media element in the constructor to calling the attach method. 
Resolves #38

Refactor ShakaPlayer initialization

---

packages/auth/package.json
packages/auth/src/auth/auth.test.ts
packages/auth/src/storage/storage.test.ts
packages/common/package.json
packages/event-producer/package.json
packages/event-producer/src/dispatch/dispatch.test.ts
packages/event-producer/src/monitor/monitor.test.ts
packages/event-producer/src/queue/queue.test.ts
packages/event-producer/src/scheduler/scheduler.test.ts
packages/event-producer/src/submit/submit.test.ts
packages/event-producer/src/uuid/uuid.test.ts
packages/player-web-components/package.json
packages/template/package.json
packages/true-time/package.json

- Switch vitest to run concurrently by default.
- Had to make some tests with timing or reused mock resources sequential.

make vitest run concurrent by default.

---

packages/auth/examples/client-credentials.js
packages/auth/examples/login-redirect.js
packages/auth/src/auth/auth.test.ts
packages/auth/src/auth/auth.ts
packages/auth/src/types.ts

To make the config even simpler we removed the required `scopes` param. If not supplied we will use an empty array internally.

We decide to make scopes optional to pass to `init`

---

packages/auth/src/auth/auth.test.ts
packages/auth/src/auth/auth.ts
packages/common/src/credentialsProvider.ts

We agreed to simplify the flow when the credentials get updated. In case you are already listening to the bus, the credentials will now be sent with the "CredentialsUpdatedMessage" event as `payload`.

Send credentials with CredentialsUpdatedMessage

---

packages/auth/src/auth/auth.ts
packages/auth/src/fixtures.ts

From now on clientSecret will be sent for all auth methods when provided.
Internal testing is done and code can be reviewed.
Internal Ticket: WIMPWC-10630

To be more consistent we added the clientSecret in all requests to backend

---

.github/workflows/fossa-scan.yml
.github/workflows/pull-request.yml

So we can catch licensing and security violations early

Add FOSSA scans

---

packages/event-producer/package.json
packages/event-producer/src/index.ts
packages/event-producer/src/send/send.test.ts
packages/event-producer/src/send/send.ts
packages/event-producer/src/types.ts
packages/event-producer/test/demo/demo.ts
packages/event-producer/test/fixtures/events.ts

* rename dispatchEvent to sendEvent
* bump version for event-producer change
cherry picked from the vites github action branch.

Haff/change dispatch to send (#46)

---

packages/auth/src/auth/auth.test.ts
packages/auth/src/auth/auth.ts
packages/auth/src/fixtures.ts
packages/auth/src/index.ts
packages/auth/src/types.ts
packages/auth/vite.config.ts

This was found during testing by @osmestad and led to an update of the spec.
We are now re-requesting (upgrading) tokens also for client credentials when the clientId or clientSecret changes in the init.

Fixed an issue with client credentials were token wasn't upgraded properly

---

packages/auth/package.json

Several small improvements in auth.
- empty scopes for `init` can be omitted
- credentials are now sent with bus event
- token upgrade for clientCredentials is fixed
- clientSecret will be passed along in all auth flows

Bump auth to release a fresh version

---

packages/player/src/internal/handlers/load.ts
packages/player/src/internal/helpers/playback-info-resolver.ts
packages/player/src/player/basePlayer.ts
packages/player/src/player/shakaPlayer.ts
packages/true-time/src/index.test.ts
packages/true-time/src/index.ts

This should be a simpler approach that has less risk of clock drift that can happen with `performance.now()` used over idle time-spans.
Using our `trueTime.now()` when setting performance marks should ensure all timestamps are of the same type/time-scale.

Convert TrueTime to use Date.now

---

.github/workflows/release-to-npm.yml

* Needs to disable git-checks (as this is ran from a tag, not from `main`)
* Needs to publish recursively as this is a monorepo and we run the command from root

Tweaks to PNPM publishing

---

.github/workflows/release-to-npm.yml

As it broke publishing of packages with dependencies on other packages in the monorepo (also it should not be needed).

Stop cleaning too much

---

package.json
pnpm-lock.yaml
vitest.workspace.ts

As current config was not picked up by IDE extension

Fix for running Vitest in VSCode

---

packages/event-producer/package.json
packages/event-producer/src/monitor/index.ts
packages/event-producer/src/send/send.test.ts
packages/event-producer/src/send/send.ts
packages/event-producer/src/types.ts
packages/event-producer/src/utils/headerUtils.test.ts
packages/event-producer/src/utils/headerUtils.ts

Confirmed that several types of events are now coming through when I point my local instance towards prod and check the tables. The error was due to the timestamp being a string.

TIP-401: Fix issue with timestamp that broke CDF events

---

package.json
packages/player/package.json
patches/shaka-player@4.8.1.patch
pnpm-lock.yaml

- Update shaka-player to version 4.8.1
- Remake the patch with [`pnpm patch`](https://pnpm.io/cli/patch) based on https://gist.github.com/Security2431/2b28f17e11870bb4b0e347673e16d5ba

Update shaka-player to 4.8.1 with TypeScript support.

---

packages/auth/examples/authorization-code.html
packages/auth/examples/authorization-code.js
packages/auth/examples/shared.js

After we got a report (#119) that the authroization code example (formerly called "login redirect") doesn't work I started digging. We found out that in the example code I used an internal api to get e.g. the userId. 
I changed the example code to use the same endpoint (search) to demonstrate the token is working.
Alongside we are also extracting the userId from the access token, which is only present in this flow and not at e.g. client credentials.
Also fixed some minor type issues in the js doc comments in `shared.js`

Removed internal api from auth example

---

.github/scripts/CheckChangelogs.main.kts
.github/workflows/check-changelog-files.yml
.github/workflows/pull-request.yml
README.md
packages/auth/CHANGELOG.md
packages/common/CHANGELOG.md
packages/event-producer/CHANGELOG.md
packages/player-web-components/CHANGELOG.md
packages/true-time/CHANGELOG.md

- Added changelog files to all the modules
- Added a check for changelog files to the pull request workflow. If a version bump is detected, it verifies that the new version is mentioned in the module's changelog file.

Enforce changelog update when version bump detected 

---

packages/auth/examples/authorization-code.js
packages/auth/src/auth/auth.test.ts
packages/auth/src/auth/auth.ts

During testing we found out, that not providing the `clientUniqueKey` leads no an error. Problem was we were still sending the param to the API, but as an empty string.
This PR cleans that up and adds a test for the case.

Fix omitting clientUniqueKey (was sent as empty string)

---

packages/auth/src/auth/auth.test.ts
packages/auth/src/auth/auth.ts

During internal testing we figured out that requesting client credentials can trigger wrong token upgrade requests.
This PR makes sure we only compare client secrets if we have one persisted actually.

Stop upgrading token if no clientSecret was present

---

packages/auth/src/auth/auth.test.ts
packages/auth/src/auth/auth.ts

Client credentials doesn't support scopes, therefore we remove passing it. This should make it simpler to change auth methods to e.g. PKCE after init.

Removing adding passed scopes when using client credentials

---

packages/player/src/internal/handlers/load.ts
packages/player/src/internal/handlers/set-next.ts
packages/player/src/player/index.ts
packages/player/src/player/shakaPlayer.ts

- Switch hls config for demo playback to be set on demand instead of on demand + on init with passing of flags.
- Limit the setting to only FairPlay enabled environments, to prevent the logic to run on widevine systems.
Doing `unload()` after the on demand config changes seems to have been the secret sauce!

[Player] Switch safari config for demo playback to be set on demand

---

packages/auth/src/auth/auth.test.ts
packages/auth/src/auth/auth.ts

To follow up #175 we are now also remove the scope check for client credentials.

Omitting scope validity check for client credentials

---

packages/player/CHANGELOG.md
packages/player/package.json

- More solid fix for demo content in safari (#173)
- Fix transitions from MAX in native player to LOW/HIGH in shaka player causing playback to stop (#177)
- Fix some transitions between players causing reset to not work correctly leading to simultaneous playback (#177)

[Player] Release v0.4.2

---

packages/player/src/player/nativePlayer.ts

This fixes one of the conditions in which users are kicked out of exclusive mode. I think this is the main condition.
I tested this with the boombox playlist and quite a lot of connecting and disconnecting.
This PR is combined with: https://github.com/tidal-engineering/webclient-app/pull/5554

MF-315: Prevent the web from setting the device in state when setting the device fails in player.

---

packages/player/CHANGELOG.md
packages/player/package.json

This is to fix the problem where a user is thrown out of exclusive mode when restoring device settings on the player.

Bump version to create a release

---

.vscode/settings.json
package.json
renovate.json

* PNPM reads workspaces from config file (so remove from `package.json`)
* Remove Prettier config from `package.json` (should be read from eslint-config package)
* Stop blocking `openapi-fetch` updates in Renovate (as we are now on latest `openapi-typescript`)
* Update eslint vscode configuration (no longer experimental)

Settings cleanup

---

packages/player/CHANGELOG.md
packages/player/package.json

- Rework reset state for native player to avoid incorrect states. (Could be the trigger for various "wrong track displayed" issues.)

[Player] Release v0.5.1

---

packages/player/CHANGELOG.md
packages/player/package.json

- Handle products that are not preloadable in the shaka-player PreloadManager.

Version 0.5.2

---

packages/player/src/internal/handlers/set-next.ts
packages/player/src/player/shakaPlayer.ts

Fix steaming-session-id linked to wrong playback info on some preloads. Causing some instances of wrong media product transitions with setNext in various cases.

[Player] Fix steaming-session-id linked to wrong playback info on some preloads

---

packages/player/src/internal/index.ts

The `CredentialsProvider` from the Auth module uses a different event `type` (name) than the Player module was expecting.

Listen to correct Auth event in Player

---

.npmrc
package.json
packages/api/package.json
packages/auth/package.json
packages/common/package.json
packages/event-producer/package.json
packages/player-web-components/package.json
packages/player/package.json
packages/template/package.json
packages/true-time/package.json
pnpm-lock.yaml

Removes Vitest from Player (as it is not needed yet?), and adds explicit Chai types for Player package (only).
Should unblock Vitest update

Partially convince Vitest, Chai and Player to get along

---

packages/player/src/api/index.ts
packages/player/src/internal/handlers/get-media-product.test.ts
packages/player/src/internal/handlers/get-next-media-product.test.ts
packages/player/src/internal/handlers/get-next-media-product.ts

Currently applications using the Web SDK needs to store and maintain their own state with regards to if something has been [set as next](https://github.com/tidal-music/tidal-sdk-web/blob/main/packages/player/src/internal/handlers/set-next.ts) or not. This PR adds a method - `getNextMediaProduct()` - that returns a `MediaProduct | null`.

Add handler for getNextMediaProduct

---

packages/api/package.json
packages/auth/package.json
packages/event-producer/package.json
packages/player-web-components/package.json
packages/player/package.json
packages/template/package.json

According to build output, `default` should be the last entry to not override others.

Fix exports order

---

packages/event-producer/src/queue/queue.ts

This should make it easier to consume the module in other projects that use Vite as their bundler.

Simplify worker URL import in event producer queue

---

.github/workflows/check-changelog-files.yml
.github/workflows/trigger-releases.yml

As there was a security issue with the package: https://semgrep.dev/blog/2025/popular-github-action-tj-actionschanged-files-is-compromised/
We should switch to use git SHAs for all actions used.

Switch to safe version of `tj-actions/changed-files`

---

.github/actions/check-api-pr/action.yml
.github/workflows/check-tidalapi-spec.yml
.github/workflows/generate-tidal-api.yml
packages/api/bin/tidal-api-oas.json

This PR adds to GH Action workflows:
1. `check-tidalapi-spec`: Runs daily, and when it detects chhnges to the API, it triggers
2. `generate-tidal-api` which handles code generation, commiting, pushing to a PR.
We also commit the json file, as a reference for the next daily check.
These addtions mean, that once merged, PRs with API updates will be opened automatically. If an already open PR is found,it will be updated.
* Add TidalAPI spec check workflow (455ecf9)

Automatic API update PR generation

---

packages/auth/src/auth/auth.test.ts
packages/auth/src/auth/auth.ts

In case the secret and client id changed, it was possible to land in an endless loop of upgrading the token because the condition for if we need to upgrade was never changed. This PR updates the `previousClientSecret` in case a successful "upgrade" has happened. (an upgrade in this situation is just a token fetch)

Stop endless upgrade loop when client secret changed

---

.github/workflows/generate-tidal-api.yml

As it caused:
Error: Error: Multiple versions of pnpm specified:
- version 10 in the GitHub Action config with the key "version"
- version pnpm@10.14.0 in the package.json with the key "packageManager" Remove one of these versions to avoid version mismatch errors like ERR_PNPM_BAD_PM_VERSION

Remove version for pnpm/action-setup in the Tidal API workflow

---

packages/player/src/api/interfaces.ts
packages/player/src/internal/event-tracking/play-log/index.test.ts
packages/player/src/internal/event-tracking/play-log/index.ts
packages/player/src/internal/helpers/manifest-parser.ts
packages/player/src/internal/helpers/playback-info-resolver.test.ts
packages/player/src/internal/helpers/playback-info-resolver.ts
packages/player/src/player/index.ts
packages/player/src/player/shakaPlayer.ts

- Updated MediaProduct and StreamInfo types to exclude 'demo'.
- Removed demo-related tests and playback info functions.
- Adjusted player configuration and playback logic to reflect the removal of 'demo' support.
- Ensured all references to 'demo' are eliminated from event tracking and playback resolution.

Player: Remove support for 'demo' product type

---

.github/workflows/generate-tidal-api.yml

Added a command to format the commit body for better readability, ensuring changes in both the generated file and spec file are clearly presented. (was printing '\n' before)

Enhance commit message formatting in Tidal API workflow

---

.github/workflows/generate-tidal-api.yml

Looks like pnpm needs to be present before node 😄 
Also added some detailing on the PR description, so you can easily see which API version this was generated from.

Fix failing tidalapi generation
